# (Throughout, leave out entries for None. Writing in `None` values will get
# you the string "None".)


## Main Config
# Model
# "EleutherAI/pythia-70m"
# "meta-llama/Llama-2-7b-hf"
# "meta-llama/Llama-2-70b-hf"
# "rasp"
MODEL_DIR: "EleutherAI/pythia-70m"

# Layers Slice to Cache Activations From
# Put a Python slice here, in str format. Put ":" to use data from all model
# layers.
ACTS_LAYERS_SLICE: "1:3"

# Autoencoder Size
PROJECTION_FACTOR: 10

# Save Files
PROMPT_IDS_FILE: "activations_prompt_ids.npy"
ACTS_DATA_FILE: "activations_dataset.pt"
ENCODER_FILE: "learned_encoder.pt"
BIASES_FILE: "learned_biases.pt"
TOP_K_INFO_FILE: "token_info.csv"

# Autoencoder Training
LAMBDA_L1: 1e-2
LEARNING_RATE: 3e-3
TRAINING_BATCH_SIZE: 8
NUM_WORKERS: 8
ACCUMULATE_GRAD_BATCHES: 4

# Directed Graph
# None for unrestricted plotting.
BRANCHING_FACTOR: 5
DIMS_PLOTTED_LIST:


## Stable Dev Constants
# Reproducibility
SEED: 0

# `wandb` logging
WANDB_PROJECT: "sparse_circuit_discovery"
WANDB_ENTITY: "davidudell"

# `collect_acts_webtext.py`
NUM_SEQUENCES_EVALED: 50
MAX_SEQ_LEN: 100

# `train_autoencoder.py`
LOG_EVERY_N_STEPS: 1
EPOCHS: 150
SYNC_DIST_LOGGING: True

# `top_tokens.py`
DIMS_IN_BATCH: 500
TOP_K: 6

# `feature_web_webtext.py`
# NUM_SEQUENCES_INTERPED is drawn from the other end of the same indices as
# NUM_SEQUENCES_EVALED in `collect_acts_webtext.py`.
NUM_SEQUENCES_INTERPED: 100
MAX_SEQ_INTERPED_LEN: 500

# `feature_web_mc.py`
NUM_QUESTIONS_INTERPED: 500
