## Config Notes
# Throughout, leave out entries for None. Writing in `None` values will get
# you the string "None". Key params here:
ACTS_LAYERS_SLICE: "3:6"
INIT_THINNING_FACTOR: 0.001
NUM_SEQUENCES_INTERPED: 1
SEQ_PER_DIM_CAP: 100

# Only pin single dims per layer.
DIMS_PINNED:

# Here you can freely pin multiple dims per layer.
VALIDATION_DIMS_PINNED:
  6: [8339, 14104, 18854]
  7: [2118]

#
## Main Config
# Model
# "EleutherAI/pythia-70m"
# "meta-llama/Llama-2-7b-hf"
# "meta-llama/Llama-2-70b-hf"
MODEL_DIR: "openai-community/gpt2"

# Prompt
PROMPT: "Copyright (C"

# Layers Slice to Cache Activations From
# Put a Python slice here, in str format. Put ":" to use data from all model
# layers.
# ACTS_LAYERS_SLICE: "4:6"

# Autoencoder Size
PROJECTION_FACTOR: 32

# Save Files
PROMPT_IDS_FILE: "activations_prompt_ids.npy"
ACTS_DATA_FILE: "activations_dataset.pt"
ENCODER_FILE: "learned_encoder.pt"
ENC_BIASES_FILE: "learned_enc_biases.pt"
DECODER_FILE: "learned_decoder.pt"
DEC_BIASES_FILE: "learned_dec_biases.pt"
TOP_K_INFO_FILE: "token_info.csv"
GRAPH_FILE: "cognition_graph.svg"
GRAPH_DOT_FILE: "cognition_graph.dot"

# Autoencoder Training
LAMBDA_L1: 1e-2
LEARNING_RATE: 3e-3
TRAINING_BATCH_SIZE: 8
NUM_WORKERS: 8
ACCUMULATE_GRAD_BATCHES: 4

# Cognition Graph
# A coefficient of 0.0 means "ablate features." Disable branching and pinning
# to plot every ablation effect. Dims are pinned by setting a layer and dim
# index as keys and values.
BRANCHING_FACTOR: 5
# INIT_THINNING_FACTOR: 0.01
LOGIT_TOKENS: 10
# DIMS_PINNED:
THRESHOLD: 0.2

# Validate Circuits
# VALIDATION_DIMS_PINNED:

#
## Stable Dev Constants
# `wandb` logging
WANDB_PROJECT: "sparse_circuit_discovery"
WANDB_ENTITY: "davidudell"

# Reproducibility
SEED: 0

# `collect_acts.py`
NUM_SEQUENCES_EVALED: 1000
MAX_SEQ_LEN: 100

# `train_autoencoder.py`
LOG_EVERY_N_STEPS: 1
EPOCHS: 150
SYNC_DIST_LOGGING: True

# `contexts.py`
TOP_K: 6
VIEW: 5

# `cognition_graph_webtext.py`
# NUM_SEQUENCES_INTERPED is drawn from the other end of the same indices as
# NUM_SEQUENCES_EVALED in `collect_acts.py`.
# NUM_SEQUENCES_INTERPED: 250
MAX_SEQ_INTERPED_LEN: 100
# SEQ_PER_DIM_CAP: 350

# `cognition_graph_mc.py`
# Currently, only NUM_QUESTIONS_INTERPED: 1 is really supported. Larger values
# are computational waste.
NUM_QUESTIONS_INTERPED: 1
MAX_NEW_TOKENS: 1
NUM_RETURN_SEQUENCES: 1
NUM_SHOT: 6
